# Generated by Django 2.2 on 2019-10-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='project',
        ),
    ]
